package com.example.sovkombank_team_challenge_it_amnezia.services.firebaseMessaging

import com.example.sovkombank_team_challenge_it_amnezia.mvp.BaseView

interface FirebaseMessagingItAmnesiaView: BaseView {
}